---
- name: Install packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
      - htop

  # TODO: Support to Arch distros
  # pacman:
  #   name:
  #     - vim
